version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./all_my_dockers/Dockerfile.frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: ./all_my_dockers/Dockerfile.backend
    ports:
      - '8000:8000'
    environment:
      - RDF_ENDPOINT=http://graphdb:7200/  # Use graphdb service name here
    depends_on:
      - graphdb
    networks:
      - app-network

  graphdb:
    image: ontotext/graphdb:10.6.4
    container_name: graphdb
    ports:
      - '7200:7200'  # Exposes GraphDB UI on localhost:7200
    environment:
      - GRAPHDB_HOME=/opt/graphdb/home
      - JAVA_OPTS=-Xmx4g -Xms2g
    volumes:
      - graphdb-data:/opt/graphdb/home
      - ./all_my_dockers/graphdb/config:/opt/graphdb/home/config
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  graphdb-data:
