# Dockerfile.frontend

FROM node:18 as builder

WORKDIR /app

COPY ../frontend/la-roche-posay-app/package.json .
COPY ../frontend/la-roche-posay-app/package-lock.json .
RUN npm install

COPY ../frontend/la-roche-posay-app .


FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/ .

EXPOSE 3000

CMD ["npm", "run", "dev"]
